# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9e4816a5459e9dd80843ca6989e038fd86127f53d234a2d79ffd7b16ccaafd2fdde24db9dcdaf7912da1e02bcf497325036c3f075e44dc5d21714908d607ee

test:
  secret_key_base: a959764a579262687dc401a44252e36cbbb421f47768cf7e60edb744def026518079949dbb5c1c14c10e70028a5653e87233a589c137944eefcb39b92b80c726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
